name: make_lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          COVERAGE_KEY: ${{ secrets.CoverageKey }}
      - run: npm install
        env:
          CI: true
      - run: make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          COVERAGE_KEY: ${{ secrets.CoverageKey }}
        with:
          coverageCommand: make test-c
          debug: true

steps:
  - name: Hello world action
    with: # Set the secret as an input
      super_secret: ${{ secrets.SuperSecret }}
    env: # Or as an environment variable
      super_secret: ${{ secrets.SuperSecret }}
